# Generated by Django 4.2.11 on 2026-04-02 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jenis Izin/Cuti')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('max_days_per_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maks. Hari/Tahun')),
                ('requires_document', models.BooleanField(default=False, verbose_name='Wajib Lampiran')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jenis Cuti',
                'verbose_name_plural': 'Jenis Cuti',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('total_days', models.PositiveIntegerField(default=0, verbose_name='Total Hari')),
                ('reason', models.TextField(verbose_name='Alasan')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_docs/%Y/%m/', verbose_name='Lampiran')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dibatalkan', 'Dibatalkan')], default='menunggu', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Review')),
                ('review_note', models.TextField(blank=True, null=True, verbose_name='Catatan Review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave.leavetype', verbose_name='Jenis Cuti')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Permohonan Cuti/Izin',
                'verbose_name_plural': 'Permohonan Cuti/Izin',
                'ordering': ['-created_at'],
            },
        ),
    ]
