# Generated by Django 4.2.11 on 2026-04-02 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Tanggal')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Hari Libur')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Hari Libur',
                'verbose_name_plural': 'Hari Libur',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Jadwal')),
                ('check_in_start', models.TimeField(verbose_name='Mulai Check-in')),
                ('check_in_end', models.TimeField(verbose_name='Batas Check-in (tepat waktu)')),
                ('check_out_start', models.TimeField(verbose_name='Mulai Check-out')),
                ('check_out_end', models.TimeField(verbose_name='Batas Check-out')),
                ('late_tolerance', models.PositiveIntegerField(default=15, verbose_name='Toleransi Terlambat (menit)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jadwal Kerja',
                'verbose_name_plural': 'Jadwal Kerja',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Tertentu')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], null=True, verbose_name='Hari (berulang)')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Berulang')),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.workschedule', verbose_name='Jadwal')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Jadwal Staff',
                'verbose_name_plural': 'Jadwal Staff',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Check-in')),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='selfies/%Y/%m/', verbose_name='Foto Check-in')),
                ('check_in_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alamat Check-in')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Check-out')),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_photo', models.ImageField(blank=True, null=True, upload_to='selfies/%Y/%m/', verbose_name='Foto Check-out')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('terlambat', 'Terlambat'), ('pulang_awal', 'Pulang Awal'), ('absen', 'Absen'), ('izin', 'Izin/Cuti'), ('libur', 'Hari Libur'), ('wfh', 'WFH')], default='hadir', max_length=20, verbose_name='Status')),
                ('work_duration', models.DurationField(blank=True, null=True, verbose_name='Durasi Kerja')),
                ('is_overtime', models.BooleanField(default=False, verbose_name='Lembur')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workschedule', verbose_name='Jadwal')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Rekap Presensi',
                'verbose_name_plural': 'Rekap Presensi',
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
